### ISSUE TITLE
In NestedListView Unable perform onScrollListener for performing loadmore data

### ISSUE THREAD

**Issue by krunal131987** [wangjiegulu/AndroidBucket#2]
How to perform load more data using webservice while reaching at last position of listview

**Comment by wangjiegulu** [comment]
You can add a footerView(load more progress) to the ListView, and than use the adapter which extends `ABaseAdapter`(https://github.com/wangjiegulu/AndroidBucket/blob/master/src/com/wangjie/androidbucket/adapter/ABaseAdapter.java). The `ABaseAdapter` can set `OnAdapterScrollListener`(https://github.com/wangjiegulu/AndroidBucket/blob/master/src/com/wangjie/androidbucket/adapter/listener/OnAdapterScrollListener.java). The `OnAdapterScrollListener` has an method `void onBottomWhenScrollIdle(AbsListView view)`, execute load more data in this method.

You also can use the `RecyclerView` instead of ListView, set `OnRecyclerViewScrollLocationListener`(https://github.com/wangjiegulu/AndroidBucket/blob/master/src/com/wangjie/androidbucket/support/recyclerview/listener/OnRecyclerViewScrollLocationListener.java) to the `ABaseLinearLayoutManager`(https://github.com/wangjiegulu/AndroidBucket/blob/master/src/com/wangjie/androidbucket/support/recyclerview/layoutmanager/ABaseLinearLayoutManager.java), and than execute load more data in `void onBottomWhenScrollIdle(RecyclerView recyclerView);`method.

enjoy it!
